trigger:
  branches:
    include:
      - main

pool: TerraPulse agent

stages:
  # - stage: stage1
  #   displayName: install_init_fmt_validate 
  #   jobs:
  #     - job: terraoforminstall_terraforminit
  #       displayName: terraform_install_init
  #       steps:
  #       - task: TerraformInstaller@1
  #         displayName: terraform install
  #         inputs:
  #           terraformVersion: 'latest'
  #       - task: TerraformTask@5
  #         displayName: terraform init
  #         inputs:
  #           provider: 'azurerm'
  #           command: 'init'
  #           workingDirectory: '$(System.DefaultWorkingDirectory)/Envoirnment/Dev/'
  #           backendServiceArm: 'Ajay_Dec_ServiceConnection'
  #           backendAzureRmOverrideSubscriptionID: '009fad33-c09c-4841-af38-57dd79870d40'
  #           backendAzureRmResourceGroupName: 'ajayrgtfstate'
  #           backendAzureRmStorageAccountName: 'ajaystgtfstate'
  #           backendAzureRmContainerName: 'ajaycontainer'
  #           backendAzureRmKey: 'ajay.tfstate'

  #     - job: terraformfmt_terrraformvalidate
  #       displayName: terraform fmt and validate
  #       dependsOn: terraoforminstall_terraforminit
  #       steps:
  #       - task: TerraformTask@5
  #         displayName: terraform init
  #         inputs:
  #           provider: 'azurerm'
  #           command: 'init'
  #           workingDirectory: '$(System.DefaultWorkingDirectory)/Envoirnment/Dev/'
  #           backendAzureRmUseEntraIdForAuthentication: false
  #           backendServiceArm: 'Ajay_Dec_ServiceConnection'
  #           backendAzureRmOverrideSubscriptionID: '009fad33-c09c-4841-af38-57dd79870d40'
  #           backendAzureRmResourceGroupName: 'ajayrgtfstate'
  #           backendAzureRmStorageAccountName: 'ajaystgtfstate'
  #           backendAzureRmContainerName: 'ajaycontainer'
  #           backendAzureRmKey: 'ajay.tfstate'
        
  #       - task: TerraformTask@5
  #         displayName: terraform fmt
  #         inputs:
  #           provider: 'azurerm'
  #           command: 'custom'
  #           commandOptions: 'fmt -recursive'
  #           outputTo: 'console'
  #           environmentServiceNameAzureRM: 'Ajay_Dec_ServiceConnection'
  #       - task: TerraformTask@5
  #         displayName: terraform validate
  #         inputs:
  #           provider: 'azurerm'
  #           command: 'validate'
  #           workingDirectory: '$(System.DefaultWorkingDirectory)/Envoirnment/Dev/'

  - stage: stage2
    displayName: Security_scanning
    # dependsOn: stage1
    jobs:
      - job: terraform_scanning
        displayName: "Terraform Security Scanning"
        steps:
        - task: tfsec@1
          displayName: tfsec scanning
          inputs:
            version: 'v1.26.0'
            dir: '$(System.DefaultWorkingDirectory)'
        
        - task: PowerShell@2
          displayName: tflint
          inputs:
            targetType: 'inline'
            script: |
              tflint --init
              tflint
            workingDirectory: '$(System.DefaultWorkingDirectory)'
        - task: PowerShell@2
          displayName: trivy scanning
          # continueOnError: true
          inputs:
            targetType: 'inline'
            # script: 'trivy fs . || true'
            workingDirectory: '$(System.DefaultWorkingDirectory)'
        - task: PowerShell@2
          displayName: checkov scanning
          continueOnError: true
          inputs:
            targetType: 'inline'
            script: 'checkov -d .'
            workingDirectory: '$(System.DefaultWorkingDirectory)'
        # - task: Go@0
        #   inputs:
        #     command: 'custom'
        #     customCommand: 'go mod init "testdev" go mod tidy go get github.com/gruntwork-io/terratest/modules/files@v0.46.16 go mod tidy go test -v'
        #     workingDirectory: '$(System.DefaultWorkingDirectory)/test'
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              cd /test
              go mod init "testdev"
              go mod tidy
              go get github.com/gruntwork-io/terratest/modules/files@v0.46.16
              go mod tidy
              go test -v
            workingDirectory: '$(System.DefaultWorkingDirectory)'

  # - stage: stage3
  #   displayName: terraform plan
  #   # dependsOn:stage2
  #   jobs:
  #     - job: terraform_plan
  #       displayName: terraform plan
  #       steps:
  #       - task: TerraformTask@5
  #         displayName: terraform init
  #         inputs:
  #           provider: 'azurerm'
  #           command: 'init'
  #           workingDirectory: '$(System.DefaultWorkingDirectory)/Envoirnment/Dev/'
  #           backendAzureRmUseEntraIdForAuthentication: false
  #           backendServiceArm: 'Ajay_Dec_ServiceConnection'
  #           backendAzureRmOverrideSubscriptionID: '009fad33-c09c-4841-af38-57dd79870d40'
  #           backendAzureRmResourceGroupName: 'ajayrgtfstate'
  #           backendAzureRmStorageAccountName: 'ajaystgtfstate'
  #           backendAzureRmContainerName: 'ajaycontainer'
  #           backendAzureRmKey: 'ajay.tfstate'
  #       - task: TerraformTask@5
  #         displayName: terraform plan
  #         inputs:
  #           provider: 'azurerm'
  #           command: 'plan'
  #           workingDirectory: '$(System.DefaultWorkingDirectory)/Envoirnment/Dev/'
  #           environmentServiceNameAzureRM: 'Ajay_Dec_ServiceConnection'

  # - stage: stage4
  #   displayName: manualValidation
  #   # dependsOn: stage3
  #   jobs:
  #     - job: manual_validation
  #       displayName: manual validation
  #       pool: server
  #       steps:
  #       - task: ManualValidation@1
  #         inputs:
  #           notifyUsers: 'Ajay'
  #           instructions: 'check and approve'

  # - stage: stage5
  #   displayName: terraformApply
  #   # dependsOn: stage3
  #   jobs:
  #     - job: terraform_apply
  #       displayName: terraformApply
  #       steps:
  #       - task: TerraformTask@5
  #         displayName: terraform init
  #         inputs:
  #           provider: 'azurerm'
  #           command: 'init'
  #           workingDirectory: '$(System.DefaultWorkingDirectory)/Envoirnment/Dev/'
  #           backendAzureRmUseEntraIdForAuthentication: false
  #           backendServiceArm: 'Ajay_Dec_ServiceConnection'
  #           backendAzureRmOverrideSubscriptionID: '009fad33-c09c-4841-af38-57dd79870d40'
  #           backendAzureRmResourceGroupName: 'ajayrgtfstate'
  #           backendAzureRmStorageAccountName: 'ajaystgtfstate'
  #           backendAzureRmContainerName: 'ajaycontainer'
  #           backendAzureRmKey: 'ajay.tfstate'
  #       - task: TerraformTask@5
  #         displayName: terraform apply
  #         inputs:
  #           provider: 'azurerm'
  #           command: 'apply'
  #           workingDirectory: '$(System.DefaultWorkingDirectory)/Envoirnment/dev/'
  #           environmentServiceNameAzureRM: 'Ajay_Dec_ServiceConnection'
  #           environmentAzureRmOverrideSubscriptionID: '009fad33-c09c-4841-af38-57dd79870d40'


